version: '3.1'
secrets:
  mongo-root-passwd:
    file: mongo-root-passwd
  mongo-user-passwd:
    file: mongo-user-passwd
networks:
  app-net:
    driver: bridge
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-net
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-passwd
      MONGO_INITDB_USERNAME: ingaia
      MONGO_INITDB_PASSWORD_FILE: /run/secrets/mongo-user-passwd
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo-volume:/data/db
    secrets:
      - mongo-root-passwd
      - mongo-user-passwd
    networks:
      - app-net
  real_estate_value_service:
    build: real-estate-value-service
    container_name: real_estate_value_service
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
      - square_meter_value_service
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    networks:
      - app-net
  square_meter_value_service:
    build: square-meter-value-service
    container_name: square_meter_value_service
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    networks:
      - app-net